version: '2'

services:
  influxdb:
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8096:8096/udp"
    volumes:
      - /var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
